name = "life-station-api"
main = "./src/index.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# KV 存储绑定 - 使用你的真实 namespace ID
[[kv_namespaces]]
binding = "BOTTLES_KV"
id = "88db0ea1da524dc59322a3b68292d7e1"
preview_id = "10c09fdf896e47c38e08c30030b527b7"

# 环境变量
[vars]
ENVIRONMENT = "development"

# 开发环境配置
[env.development.vars]
ENVIRONMENT = "development"

# 生产环境配置
[env.production.vars]
ENVIRONMENT = "production"